### ISSUE TITLE
Can't delete first favLocation

### ISSUE THREAD

**Issue by jwu910** [rainrivas/travel-delta#2]
After adding multiple favorite locations, the button to remove location only appears on new entries. Possibly change these buttons so we can "insert" or "add below" new locations to any field, as well as remove any field (unless last field--one location required).

**Comment by rainrivas** [comment]
I might have some way to handle this with my to do list repo.

**Comment by rainrivas** [comment]
Fixed in PR #6

**Comment by jwu910** [comment]
Sweet! Thanks!
