### ISSUE TITLE
Tools, Libraries, Frameworks, Lanuages?

### ISSUE THREAD

**Issue by jwu910** [rainrivas/travel-delta#3]
# What to use?
Let's begin thinking of tools that we have available to start using. We have a lot of different experience at the table including:

### Languages

- JavaScript
- HTML5
- CSS3/SASS
- Ruby
- Python
- C++
- MongoDB
- MariaDB(?)
- SQL/MySQL

### Libraries

- React
- jQuery
- YUI

### Frameworks

- Rails
- Django
- Express
- Bootstrap

### Generators, Task Runners, Package Managers, Template Engines and Others.

- Jekyll
- Yeoman
- Grunt
- Gulp
- PIP
- NPM
- Freemarker
- Handlebars
- Java Server Pages
- Liquid
- Apache

What can we leverage in to this app? I think it would be a great opportunity for everyone to learn something new. There is some really good diversity, and I don't think I have the foundation to understand how it all comes together to make that recommendation. Looking forward to discuss.

**Comment by jwu910** [comment]
Feel free to add to the lists and/or make corrections.. 

and now i'm asking myself: Should this have just been in one of the files?

**Comment by rainrivas** [comment]
Not sure. Zenhub lets us create stories similar to JIRA so maybe we should've tracked it there

**Comment by jwu910** [comment]
I can update , i wanted just a space to talk about the stuff we use/have

**Comment by jwu910** [comment]
Can close this discussion.
